version: '3.8'
services:
  app:
    depends_on:
      - database
    build:
      context: .
      target: dev
    env_file:
      - .env
    environment:
      PORT: 3001
      DEBUG_HOST: 0.0.0.0:9229
      DATABASE_URL: postgresql://user:pass@database:54320/postgres?schema=public&connect_timeout=30
    command: npm run start:debug
    ports:
      - "127.0.0.1:3001:3001"
      - "127.0.0.1:9229:9229"
    volumes:
      - ./:/home/node/app

  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: postgres
      PGPORT: 54320
    expose:
      - '54320'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db
