apiVersion: v1
kind: Secret
metadata:
  name: nest-prisma-template-database-secret
data:
  POSTGRES_DB: bmVzdC1wcmlzbWEtdGVtcGxhdGU=
  POSTGRES_USER: bmVzdC1wcmlzbWEtdGVtcGxhdGU=
  POSTGRES_PASSWORD: TEJjZHNvMDhiJmFhc2QoY2syKmQhcA==