apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: nest-prisma-template-database-secret
  namespace: standalone
spec:
  encryptedData:
    POSTGRES_DB: AgALTKrEOFW05YaWfDP4WAQilFtXdUHv0SS01Rn8mj2zns3Sjl8h0rxlnB2MtFEpy4uGOeHveeJjT37BXiDdPKbIxnKggA+ymlGWu6zzgJ18MSJTDiawvHXWe3/ha6Rdp5Tf89obz9YIGVqtEK+yx/oXXDTNt4/uZ28rA/7XqfdzZ0a6vWGOXnoZ+1L3U1qEI62DTEac7RpvlYyXg4mlfWdszdlfg+wFWz1m8yDLfMzk+tpFM9GTyq8JL4NY2EQk1KKGmmixBvehoUodOv4rTLPNGUK/EEzFT+FlEaq/gCnSW+eJKHcjnF10ZCTRePSfM+sKkN/7jd5daoMZ3ZDrTp5DaRqKzqrKaSOVDilG9E1Hh83qcW1A9FEhxUVH7gCU3dP5RnZFl8IxVTfYOuXH33eo3zyZMp8TisXfqe/kD1pgCcUt+UtN/Oplmk5Xlgxsd3EFRoHs/HBAwQkUEoM1CN9BLhS5rDfjVfL6Bfs8oIoV4d3BEqqd+yKnveDGWDJv10qFApLoASEZeyIv0c+eZN9Z9AzVu56vH8pCmIrDsgcP9/tWBeMDcotO8MOUPJrUo4BBnZxaYx1pmySxqR2yr1fOHxFJZV4RzvRw+Vh6L/X4b33LstZ3bSva34DQOXrkcoccJQeinrQ5KMbvcJyc0cL+Z/v3nNvMABsWjgLIh9f03TfFbjCiilMyr0sKh7YefVAFa4Glisw=
    POSTGRES_PASSWORD: AgCZ0YzT/zVbkXR1E/dydEu67yWwIltlwA5T8VRqHpAuKgLsFuwEnc+EZC/ybrWUwVuB37nRO+K9O7XlXOpffEetbbuaZyYk1wkO8XJCSzRBVTwGiEp95LKjIXJNlROYC0HzdnUd3PBEYQ3gSwsU2gUfqSBDVY5nZlW3ihlV77g96pT4u5aceHrJxubQ7e2BOxdb/rHCXsHaMuG2ARK5TFD1ZV4pfLKleM7d9srALPHCYbxd3B2EaJaN4EUx3FNr24x3kgrVJm4uVwQPrZmhqCauheeF/rG8cuC4xowo6FNeNhH0oLD5fNbeD4nlsF/SIEj3E0E3yzWhtX3+MrOTGeYedeUkkETtwkybQyB5aBtPxkKltAKJ0DrfrzNB/aTOIB3JRu9ZUviujVtJjz6USGQeyvuAwYm6RA/3HH0Cc1WeQGG8N0GQPDDhpd8t/ZcGhLJZtTY9izXmU+V+QqtQf3R3fHQyCl9aMDUojIWzACOuMC3nl/aw8+r2MjtUKU/oMUGBiSMcRwOa+uOsasUvHvRMAMe6FxvachU3xXaJ5uNf7xz/jmXeALgVlkGCJfVbNSfOtJipv5vlJQITrIrTDwuQrkw1JtjIeL7RtdVW1h1BZx4stlYVgaioZmV/bk5TWG5xQJALKaOoKzU8q0KX2BSgTEgbGwCo7o6xzZKDTrI0g9MOkImq9uJHgLk0XZ9DEADVRqIMkBI=
    POSTGRES_USER: AgB5QUAGEWgV+Q9Q4XSxjpu2tO+/SO0/Jut8VUCx/1zcZczj3aaBapw9+uzKMvjQZ2QFEqIvwhsI2MSCXn21HeG/wQFMfUraSYyJ2wUFMeYbLaf/SLM50FLVbVWWmv2f1Mrw7H8pn5XiFn0+3HThHOG3H6eouqQimS3eCCttOBbY+ka0nuETKTZvXMSprfcJHp/S1pdpr67UuJ/u9JirP4daY+Nbm28DiDkGw+UEkKXFo40JwcZupBRYRKgLBRpzIF+wcUpegZnWlnIJWqyKn866OchfIiak2h7td9Jd6NtfEY3jkjKpaBvBIlUhRSHlQ5v/ZZuu+dyZs0VjtM61kIu48rb/cch+2rwdE85QwZA9te6qO4XzPvXiqFiFegS0WMBQkjOQtkN/lCUooND36ndRjYFXfibjEEdYiPGhaCPElM2QmgzarqRkB/R6DxArtLo/L7OcCBtcrpfoo2S8Zl/sOiV+ZiqeevME6H1j1eN0Y4NrY1os5Wx38OOp84okLl+UBq2lDAqPyzPw0WOiLzLS1Hrqe60PoHlnFj6Ew+Z4UwDnuM9cjIpoA1KUEdaBOX1UL2NFc7hVTVnBgCW4XuEnYXp0LqxBrono/tM+3XZIeDnnJzVBHxD62saGoPONz6H1ZUNVMBdzOoQOB48LU/aVsM5HXoqEfCkWTql44b6tSUxKu6ZKS9eR5vDifxeRHm5lUWH73Ac=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: nest-prisma-template-database-secret
      namespace: standalone

