resources:
  - deployment.yml
  - service-app.yml
  - ingress.yml
  # Comment-out these lines if no database is used
  - stateful-set.yml
  - service-database.yml
configurations:
  - configuration.yml

# Keep as is
commonLabels:
  app: ${BUILD_REPOSITORY_NAME}
  sla: aws-critical
  source: ${BUILD_REPOSITORY_NAME}

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: ${BUILD_REPOSITORY_NAME}-env
  namespace: ${NAMESPACE}
  envs:
  - .env
