resources:
  - deployment.yml
  - service-app.yml
  - ingress.yml
  # Comment-out these lines if no database is used
  - statefulSet.yml
  - service-db.yml
  # Add any secrets here
  - ./secrets/database.secret.yml
configurations:
  - configuration.yml


# Add composite env vars from secrets
patches:
  - target:
      name: app
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
        - name: DB_POSTGRES_CS
          value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@${BUILD_REPOSITORY_NAME}-database:5432/$(POSTGRES_DB)?schema=public


# Keep as is
namePrefix: ${BUILD_REPOSITORY_NAME}-
commonLabels:
  app: ${BUILD_REPOSITORY_NAME}
  source: ${BUILD_REPOSITORY_NAME}

commonAnnotations:
  repositoryUrl: ${BUILD_REPOSITORY_URI}

configMapGenerator:
- name: env
  envs:
  - .env