name: Deploy code to kubernetes
on:
   push:
     branches:
       - master
env:
  DOCKER_REGISTRY: harbor.bratislava.sk
  DOCKER_USERNAME: robot$github_actions
  DOCKER_PASSWORD: ${{ secrets.HARBOR_GITHUB_ACTIONS }}
  KUBERNETES_NAMESPACE: standalone
  # kubectl get secret <service account> -n=standalone -o jsonpath='{.data.ca\.crt}' > cert.ca
  KUBERNETES_SERVICE_ACCOUNT_CERT: ${{ secrets.DEV_STANDALONE_CERT }}
  # kubectl get secret <service account secret> -n=standalone -o jsonpath='{.data.token}' | base64 --decode  > token.tmp
  KUBERNETES_SERVICE_ACCOUNT_TOKEN: ${{ secrets.DEV_STANDALONE_TOKEN }}
  KUBERNETES_SERVER_URL: https://tkg.dev.bratislava.sk
  KUBERNETES_CLUSTER: tkg-innov-dev
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v3
    - name: Install Prerequisites -  Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Installing Bratiska-cli       
      run: yarn global add bratislava/bratiska-cli
    - name: Running git fetch for Bratiska-cli 
      run: git fetch
    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v2.1
    - name: Login to Kubernetes
      uses: Azure/k8s-set-context@v2
      with:
        method: service-account
        k8s-url: https://tkgk.dev.bratislava.sk
        k8s-secret: ${{ secrets.DEV_STANDALONE }}
        
    - name: Set certificate for kuberntes
      run: echo ${{ env.KUBERNETES_SERVICE_ACCOUNT_CERT }} | base64 -d > ca.crt
        
    - name: Kubernetes set service account token
      run: kubectl config set-credentials default --token=${{ env.KUBERNETES_SERVICE_ACCOUNT_TOKEN }}
        
    - name: Kubernetes set server with certificate account token
      run: kubectl config set-cluster ${{ env.KUBERNETES_CLUSTER }}  --insecure-skip-tls-verify --server=${{ env.KUBERNETES_SERVER_URL }} --certificate-authority=ca.crt
      
    - name: Kubernetes set context adn cluster
      run: kubectl config set-context ${{ env.KUBERNETES_CLUSTER }} --cluster=${{ env.KUBERNETES_CLUSTER }} --user=default
        
    - name: Kubernetes use context
      run: kubectl config use-context ${{ env.KUBERNETES_CLUSTER }}
        
    - name: Check connection
      run: kubectl get pods -n=standalone
        
    - run: kubectl config current-context
    - name: Login to Harbor
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
    - name: Running build and deploy on Bratiska-cli 
      run: bratiska-cli deploy
