name: Deploy code to kubernetes
on:
   push:
     branches:
       - master
env:
  DOCKER_REGISTRY: harbor.bratislava.sk
  DOCKER_USERNAME: robot$github_actions
  DOCKER_PASSWORD: ${{ secrets.HARBOR_GITHUB_ACTIONS }}
  KUBERNETES_NAMESPACE: standalone
jobs:
  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v3
    - name: Install Prerequisites -  Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: Install Prerequisites - envsubst
      run: |
           sudo apt-get update
           sudo apt-get install gettext-base
    - name: Installing Bratiska-cli       
      run: yarn global add bratislava/bratiska-cli
    - name: Running git fetch for Bratiska-cli 
      run: git fetch
    - name: Login to Kubernetes
      uses: Azure/k8s-set-context@v2
      with:
        method: service-account
        k8s-url: https://tkg.dev.bratislava.sk
        # Service account secret (run kubectl get serviceaccounts <service-account-name> -o yaml and copy the service-account-secret-name)
        k8s-secret: ${{ secrets.DEV_STANDALONE }}
        resource-group: ${{ env.KUBERNETES_NAMESPACE }}
    - name: Login to Harbor
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ env.DOCKER_PASSWORD }}
    - name: Running build and deplou on Bratiska-cli 
      run: bratiska-cli deploy --dry_run
